# Introduction

*What is Classification?*

In statistics, classification is the problem of identifying which of a set of categories an observation, belongs to.
A Classification algorithm is a type Supervised Machine Learning algorithm which predicts data or the category to which the data belongs, based on the training set provided, which contains various features. 

It can be used to:
* Classify different images as cat or dog, based on different features
* Predict if a person is Covid positive or negative, based on different symptoms and tests conducted
* If a person will pass or fail in exams, based on the hours of study and the marks in practice tests
And so on...

Different types of Classificatio algorithm are:
* K-Nearest Neighbors (K-NN)
* Support Vector Machine (SVM)
* Kernel SVM
* Naive Bayes
* Logistic Regression

*About the problem...*

This problem involves classification and prediction of glass type among the 7 different types given,  
1. buildingwindowsfloatprocessed 
2. buildingwindowsnonfloatprocessed
3. vehiclewindowsfloatprocessed 
4. vehiclewindowsnonfloatprocessed (none in this database)
5. containers
6. tableware
7. headlamps. 

This is a Glass Identification Data Set from UCI. It contains 10 attributes including id.

To check which algorithm is based suited to analyse the given dataset, all the different classification models are applied on the dataset and the one with best r2 score or accuracy score is selected as the best algorithm for the given dataset!

Link to dataset: https://www.kaggle.com/uciml/glass

# Preparing the dataset to apply the model

## Importing the libraries

In [72]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [73]:
dataset = pd.read_csv('glass_classification_and_analysis_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Data Preprocessing

### Missing Values

In [74]:
np.any(np.isnan(dataset))

False

In [75]:
dataset.isnull().mean()

RI      0.0
Na      0.0
Mg      0.0
Al      0.0
Si      0.0
K       0.0
Ca      0.0
Ba      0.0
Fe      0.0
Type    0.0
dtype: float64

The dataset is free of any NaN or null values

## Splitting the dataset into the Training set and Test set

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [77]:
print(X_train)

[[ 1.51674 12.79     3.52    ...  7.9      0.       0.     ]
 [ 1.51808 13.43     2.87    ...  9.03     0.       0.     ]
 [ 1.52152 13.05     3.65    ...  9.85     0.       0.17   ]
 ...
 [ 1.51708 13.72     3.68    ...  7.88     0.       0.     ]
 [ 1.52667 13.99     3.7     ...  9.82     0.       0.1    ]
 [ 1.51321 13.       0.      ...  6.93     0.       0.     ]]

In [78]:
print(y_train)

[2 1 1 1 1 3 3 1 1 2 1 2 3 1 1 1 1 2 2 1 3 2 1 7 1 2 6 3 2 7 3 2 2 1 1 2 7
 1 1 3 7 7 2 1 1 1 2 7 1 1 2 2 7 7 7 3 2 1 2 2 5 7 1 2 1 2 2 2 1 3 1 1 1 1
 2 7 1 2 2 2 5 7 1 1 2 2 7 5 6 6 5 2 6 1 2 2 1 1 1 1 2 5 1 2 2 7 1 1 2 1 7
 2 1 1 2 5 3 1 6 2 7 1 5 2 6 3 1 6 2 2 5 2 2 3 7 2 2 1 5 2 7 5 7 1 7 1 2 2
 2 2 1 1 1 2 7 1 7 2 1 5]

In [79]:
print(X_test)

[[1.51727e+00 1.47000e+01 0.00000e+00 2.34000e+00 7.32800e+01 0.00000e+00
  8.95000e+00 6.60000e-01 0.00000e+00]
 [1.51797e+00 1.27400e+01 3.48000e+00 1.35000e+00 7.29600e+01 6.40000e-01
  8.68000e+00 0.00000e+00 0.00000e+00]
 [1.51640e+00 1.25500e+01 3.48000e+00 1.87000e+00 7.32300e+01 6.30000e-01
  8.08000e+00 0.00000e+00 9.00000e-02]
 [1.51905e+00 1.40000e+01 2.39000e+00 1.56000e+00 7.23700e+01 0.00000e+00
  9.57000e+00 0.00000e+00 0.00000e+00]
 [1.52369e+00 1.34400e+01 0.00000e+00 1.58000e+00 7.22200e+01 3.20000e-01
  1.22400e+01 0.00000e+00 0.00000e+00]
 [1.51590e+00 1.30200e+01 3.58000e+00 1.51000e+00 7.31200e+01 6.90000e-01
  7.96000e+00 0.00000e+00 0.00000e+00]
 [1.51841e+00 1.30200e+01 3.62000e+00 1.06000e+00 7.23400e+01 6.40000e-01
  9.13000e+00 0.00000e+00 1.50000e-01]
 [1.51711e+00 1.28900e+01 3.62000e+00 1.57000e+00 7.29600e+01 6.10000e-01
  8.11000e+00 0.00000e+00 0.00000e+00]
 [1.51596e+00 1.27900e+01 3.61000e+00 1.62000e+00 7.29700e+01 6.40000e-01
  8.07000e+00 0.00000e+00 2.60000e-01]
 [1.51594e+00 1.30900e+01 3.52000e+00 1.55000e+00 7.28700e+01 6.80000e-01
  8.05000e+00 0.00000e+00 9.00000e-02]
 [1.51769e+00 1.24500e+01 2.71000e+00 1.29000e+00 7.37000e+01 5.60000e-01
  9.06000e+00 0.00000e+00 2.40000e-01]
 [1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01 6.20000e-01
  8.68000e+00 0.00000e+00 3.50000e-01]
 [1.51832e+00 1.33300e+01 3.34000e+00 1.54000e+00 7.21400e+01 5.60000e-01
  8.99000e+00 0.00000e+00 0.00000e+00]
 [1.52777e+00 1.26400e+01 0.00000e+00 6.70000e-01 7.20200e+01 6.00000e-02
  1.44000e+01 0.00000e+00 0.00000e+00]
 [1.51596e+00 1.30200e+01 3.56000e+00 1.54000e+00 7.31100e+01 7.20000e-01
  7.90000e+00 0.00000e+00 0.00000e+00]
 [1.51514e+00 1.48500e+01 0.00000e+00 2.42000e+00 7.37200e+01 0.00000e+00
  8.39000e+00 5.60000e-01 0.00000e+00]
 [1.51667e+00 1.29400e+01 3.61000e+00 1.26000e+00 7.27500e+01 5.60000e-01
  8.60000e+00 0.00000e+00 0.00000e+00]
 [1.51589e+00 1.28800e+01 3.43000e+00 1.40000e+00 7.32800e+01 6.90000e-01
  8.05000e+00 0.00000e+00 2.40000e-01]
 [1.51610e+00 1.34200e+01 3.40000e+00 1.22000e+00 7.26900e+01 5.90000e-01
  8.32000e+00 0.00000e+00 0.00000e+00]
 [1.51776e+00 1.35300e+01 3.41000e+00 1.52000e+00 7.20400e+01 5.80000e-01
  8.79000e+00 0.00000e+00 0.00000e+00]
 [1.51666e+00 1.28600e+01 0.00000e+00 1.83000e+00 7.38800e+01 9.70000e-01
  1.01700e+01 0.00000e+00 0.00000e+00]
 [1.51851e+00 1.32000e+01 3.63000e+00 1.07000e+00 7.28300e+01 5.70000e-01
  8.41000e+00 9.00000e-02 1.70000e-01]
 [1.51683e+00 1.45600e+01 0.00000e+00 1.98000e+00 7.32900e+01 0.00000e+00
  8.52000e+00 1.57000e+00 7.00000e-02]
 [1.52365e+00 1.57900e+01 1.83000e+00 1.31000e+00 7.04300e+01 3.10000e-01
  8.61000e+00 1.68000e+00 0.00000e+00]
 [1.51660e+00 1.29900e+01 3.18000e+00 1.23000e+00 7.29700e+01 5.80000e-01
  8.81000e+00 0.00000e+00 2.40000e-01]
 [1.51911e+00 1.39000e+01 3.73000e+00 1.18000e+00 7.21200e+01 6.00000e-02
  8.89000e+00 0.00000e+00 0.00000e+00]
 [1.51640e+00 1.43700e+01 0.00000e+00 2.74000e+00 7.28500e+01 0.00000e+00
  9.45000e+00 5.40000e-01 0.00000e+00]
 [1.51761e+00 1.28100e+01 3.54000e+00 1.23000e+00 7.32400e+01 5.80000e-01
  8.39000e+00 0.00000e+00 0.00000e+00]
 [1.51569e+00 1.32400e+01 3.49000e+00 1.47000e+00 7.32500e+01 3.80000e-01
  8.03000e+00 0.00000e+00 0.00000e+00]
 [1.51848e+00 1.36400e+01 3.87000e+00 1.27000e+00 7.19600e+01 5.40000e-01
  8.32000e+00 0.00000e+00 3.20000e-01]
 [1.51756e+00 1.31500e+01 3.61000e+00 1.05000e+00 7.32400e+01 5.70000e-01
  8.24000e+00 0.00000e+00 0.00000e+00]
 [1.52227e+00 1.41700e+01 3.81000e+00 7.80000e-01 7.13500e+01 0.00000e+00
  9.69000e+00 0.00000e+00 0.00000e+00]
 [1.51709e+00 1.30000e+01 3.47000e+00 1.79000e+00 7.27200e+01 6.60000e-01
  8.18000e+00 0.00000e+00 0.00000e+00]
 [1.51743e+00 1.22000e+01 3.25000e+00 1.16000e+00 7.35500e+01 6.20000e-01
  8.90000e+00 0.00000e+00 2.40000e-01]
 [1.51806e+00 1.30000e+01 3.80000e+00 1.08000e+00 7.30700e+01 5.60000e-01
  8.38000e+00 0.00000e+00 1.20000e-01]
 [1.52211e+00 1.41900e+01 3.78000e+00 9.10000e-01 7.13600e+01 2.30000e-01
  9.14000e+00 0.00000e+00 3.70000e-01]
 [1.51753e+00 1.25700e+01 3.47000e+00 1.38000e+00 7.33900e+01 6.00000e-01
  8.55000e+00 0.00000e+00 6.00000e-02]
 [1.51694e+00 1.28600e+01 3.58000e+00 1.31000e+00 7.26100e+01 6.10000e-01
  8.79000e+00 0.00000e+00 0.00000e+00]
 [1.51841e+00 1.29300e+01 3.74000e+00 1.11000e+00 7.22800e+01 6.40000e-01
  8.96000e+00 0.00000e+00 2.20000e-01]
 [1.51602e+00 1.48500e+01 0.00000e+00 2.38000e+00 7.32800e+01 0.00000e+00
  8.76000e+00 6.40000e-01 9.00000e-02]
 [1.53125e+00 1.07300e+01 0.00000e+00 2.10000e+00 6.98100e+01 5.80000e-01
  1.33000e+01 3.15000e+00 2.80000e-01]
 [1.51299e+00 1.44000e+01 1.74000e+00 1.54000e+00 7.45500e+01 0.00000e+00
  7.59000e+00 0.00000e+00 0.00000e+00]
 [1.51674e+00 1.28700e+01 3.56000e+00 1.64000e+00 7.31400e+01 6.50000e-01
  7.99000e+00 0.00000e+00 0.00000e+00]
 [1.51784e+00 1.26800e+01 3.67000e+00 1.16000e+00 7.31100e+01 6.10000e-01
  8.70000e+00 0.00000e+00 0.00000e+00]
 [1.51789e+00 1.31900e+01 3.90000e+00 1.30000e+00 7.23300e+01 5.50000e-01
  8.44000e+00 0.00000e+00 2.80000e-01]
 [1.51687e+00 1.32300e+01 3.54000e+00 1.48000e+00 7.28400e+01 5.60000e-01
  8.10000e+00 0.00000e+00 0.00000e+00]
 [1.51736e+00 1.27800e+01 3.62000e+00 1.29000e+00 7.27900e+01 5.90000e-01
  8.70000e+00 0.00000e+00 0.00000e+00]
 [1.51592e+00 1.28600e+01 3.52000e+00 2.12000e+00 7.26600e+01 6.90000e-01
  7.97000e+00 0.00000e+00 0.00000e+00]
 [1.51900e+00 1.34900e+01 3.48000e+00 1.35000e+00 7.19500e+01 5.50000e-01
  9.00000e+00 0.00000e+00 0.00000e+00]
 [1.51645e+00 1.34400e+01 3.61000e+00 1.54000e+00 7.23900e+01 6.60000e-01
  8.03000e+00 0.00000e+00 0.00000e+00]
 [1.51742e+00 1.32700e+01 3.62000e+00 1.24000e+00 7.30800e+01 5.50000e-01
  8.07000e+00 0.00000e+00 0.00000e+00]
 [1.52222e+00 1.44300e+01 0.00000e+00 1.00000e+00 7.26700e+01 1.00000e-01
  1.15200e+01 0.00000e+00 8.00000e-02]
 [1.51556e+00 1.38700e+01 0.00000e+00 2.54000e+00 7.32300e+01 1.40000e-01
  9.41000e+00 8.10000e-01 1.00000e-02]
 [1.51786e+00 1.27300e+01 3.43000e+00 1.19000e+00 7.29500e+01 6.20000e-01
  8.76000e+00 0.00000e+00 3.00000e-01]]

In [80]:
print(y_test)

[7 1 2 6 5 2 2 2 1 2 1 2 3 2 2 7 2 1 3 3 5 2 7 7 2 1 7 1 2 2 1 1 2 2 2 3 1
 3 2 7 2 6 2 1 2 2 1 2 1 2 1 2 7 1]

In [81]:
from xgboost import XGBClassifier 
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

XGBoost is a decision-tree-based ensemble Machine Learning algorithm that uses a gradient boosting framework. It is used for speed and performance!

## Feature Scaling

Scaling is done and is important for classification because the distance of the points from the classes is the main principle behind classification. The data consists of some large difference between the values, hence to normalize the range of the variables, Scaling is done. Standard scaler sets the mean of the data as 0 and the other points in terms of standard deviation.

In [82]:
dataset.describe()

               RI          Na          Mg  ...          Ba          Fe        Type
count  214.000000  214.000000  214.000000  ...  214.000000  214.000000  214.000000
mean     1.518365   13.407850    2.684533  ...    0.175047    0.057009    2.780374
std      0.003037    0.816604    1.442408  ...    0.497219    0.097439    2.103739
min      1.511150   10.730000    0.000000  ...    0.000000    0.000000    1.000000
25%      1.516523   12.907500    2.115000  ...    0.000000    0.000000    1.000000
50%      1.517680   13.300000    3.480000  ...    0.000000    0.000000    2.000000
75%      1.519157   13.825000    3.600000  ...    0.000000    0.100000    3.000000
max      1.533930   17.380000    4.490000  ...    3.150000    0.510000    7.000000

[8 rows x 10 columns]

In [83]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [84]:
print(X_train)

[[-0.57016436 -0.8021311   0.59394972 ... -0.73204433 -0.36042422
  -0.5574741 ]
 [-0.12738242 -0.01596892  0.14178098 ...  0.03745343 -0.36042422
  -0.5574741 ]
 [ 1.00931153 -0.48275272  0.68438347 ...  0.59585004 -0.36042422
   1.35466909]
 ...
 [-0.4578167   0.34026082  0.70525279 ... -0.74566376 -0.36042422
  -0.5574741 ]
 [ 2.7110481   0.67192299  0.71916568 ...  0.57542089 -0.36042422
   0.56731601]
 [-1.73659739 -0.54417164 -1.85471789 ... -1.39258666 -0.36042422
  -0.5574741 ]]

In [85]:
print(X_test)

[[-3.95034190e-01  1.54407167e+00 -1.85471789e+00  1.75197496e+00
   8.54487173e-01 -6.88607851e-01 -1.70242868e-02  1.01064199e+00
  -5.57474100e-01]
 [-1.63730189e-01 -8.63550025e-01  5.66123950e-01 -1.61246920e-01
   4.37862630e-01  1.79249921e-01 -2.00886585e-01 -3.60424223e-01
  -5.57474100e-01]
 [-6.82512019e-01 -1.09694192e+00  5.66123950e-01  8.43677703e-01
   7.89389588e-01  1.65689643e-01 -6.09469468e-01 -3.60424223e-01
   4.54837002e-01]
 [ 1.93138841e-01  6.84206777e-01 -1.92128234e-01  2.44588024e-01
  -3.30288871e-01 -6.88607851e-01  4.05178026e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.72635393e+00 -3.68513524e-03 -1.85471789e+00  2.83238971e-01
  -5.25581625e-01 -2.54678965e-01  2.22337186e+00 -3.60424223e-01
  -5.57474100e-01]
 [-8.47729162e-01 -5.19604069e-01  6.35688371e-01  1.47960657e-01
   6.46174901e-01  2.47051309e-01 -6.91186045e-01 -3.60424223e-01
  -5.57474100e-01]
 [-1.83391029e-02 -5.19604069e-01  6.63514139e-01 -7.21685652e-01
  -3.69347422e-01  1.79249921e-01  1.05550578e-01 -3.60424223e-01
   1.12971107e+00]
 [-4.47903676e-01 -6.79293263e-01  6.63514139e-01  2.63913498e-01
   4.37862630e-01  1.38569088e-01 -5.89040324e-01 -3.60424223e-01
  -5.57474100e-01]
 [-8.27903105e-01 -8.02131105e-01  6.56557697e-01  3.60540865e-01
   4.50882147e-01  1.79249921e-01 -6.16279183e-01 -3.60424223e-01
   2.36698019e+00]
 [-8.34511791e-01 -4.33617580e-01  5.93949718e-01  2.25262551e-01
   3.20686977e-01  2.33491031e-01 -6.29898612e-01 -3.60424223e-01
   4.54837002e-01]
 [-2.56251789e-01 -1.21977977e+00  3.04779118e-02 -2.77199761e-01
   1.40130689e+00  7.07676992e-02  5.78825752e-02 -3.60424223e-01
   2.14202217e+00]
 [-2.49477886e-02 -7.28428400e-01  6.98296349e-01 -3.73827128e-01
  -6.98985317e-02  1.52129365e-01 -2.00886585e-01 -3.60424223e-01
   3.37929130e+00]
 [-4.80781887e-02 -1.38806761e-01  4.68733761e-01  2.05937077e-01
  -6.29737761e-01  7.07676992e-02  1.02145721e-02 -3.60424223e-01
  -5.57474100e-01]
 [ 3.07452582e+00 -9.86387867e-01 -1.85471789e+00 -1.47537912e+00
  -7.85971965e-01 -6.07246185e-01  3.69427024e+00 -3.60424223e-01
  -5.57474100e-01]
 [-8.27903105e-01 -5.19604069e-01  6.21775487e-01  2.05937077e-01
   6.33155384e-01  2.87732142e-01 -7.32044333e-01 -3.60424223e-01
  -5.57474100e-01]
 [-1.09885922e+00  1.72832843e+00 -1.85471789e+00  1.90657875e+00
   1.42734592e+00 -6.88607851e-01 -3.98368312e-01  8.02904681e-01
  -5.57474100e-01]
 [-5.93294762e-01 -6.17874343e-01  6.56557697e-01 -3.35176181e-01
   1.64452774e-01  7.07676992e-02 -2.55364302e-01 -3.60424223e-01
  -5.57474100e-01]
 [-8.51033505e-01 -6.91577047e-01  5.31341740e-01 -6.46195521e-02
   8.54487173e-01  2.47051309e-01 -6.29898612e-01 -3.60424223e-01
   2.14202217e+00]
 [-7.81642305e-01 -2.82527035e-02  5.10472414e-01 -4.12478075e-01
   8.63356719e-02  1.11448532e-01 -4.46036315e-01 -3.60424223e-01
  -5.57474100e-01]
 [-2.33121389e-01  1.06868922e-01  5.17428856e-01  1.67286130e-01
  -7.59932931e-01  9.78882545e-02 -1.25979722e-01 -3.60424223e-01
  -5.57474100e-01]
 [-5.96599105e-01 -7.16144616e-01 -1.85471789e+00  7.66375809e-01
   1.63565819e+00  6.26739084e-01  8.13760910e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.47043258e-02 -2.98495955e-01  6.70470581e-01 -7.02360178e-01
   2.68608909e-01  8.43279769e-02 -3.84748882e-01 -1.73460649e-01
   1.35466909e+00]
 [-5.40425276e-01  1.37209869e+00 -1.85471789e+00  1.05625791e+00
   8.67506690e-01 -6.88607851e-01 -3.09842020e-01  2.90105145e+00
   2.29878979e-01]
 [ 1.71313656e+00  2.88300414e+00 -5.81688989e-01 -2.38548814e-01
  -2.85607516e+00 -2.68239243e-01 -2.48554588e-01  3.12956249e+00
  -5.57474100e-01]
 [-6.16425162e-01 -5.56455422e-01  3.57430688e-01 -3.93152602e-01
   4.50882147e-01  9.78882545e-02 -1.12360293e-01 -3.60424223e-01
   2.14202217e+00]
 [ 2.12964898e-01  5.61368935e-01  7.40035001e-01 -4.89779970e-01
  -6.55776795e-01 -6.07246185e-01 -5.78825752e-02 -3.60424223e-01
  -5.57474100e-01]
 [-6.82512019e-01  1.13870679e+00 -1.85471789e+00  2.52499390e+00
   2.94647943e-01 -6.88607851e-01  3.23461450e-01  7.61357220e-01
  -5.57474100e-01]
 [-2.82686532e-01 -7.77563536e-01  6.07862602e-01 -3.93152602e-01
   8.02409105e-01  9.78882545e-02 -3.98368312e-01 -3.60424223e-01
  -5.57474100e-01]
 [-9.17120363e-01 -2.49360818e-01  5.73080392e-01  7.06587626e-02
   8.15428622e-01 -1.73317299e-01 -6.43518042e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 4.79129716e-03  2.41990548e-01  8.37425190e-01 -3.15850708e-01
  -8.64089066e-01  4.36471438e-02 -4.46036315e-01 -3.60424223e-01
   3.04185426e+00]
 [-2.99208247e-01 -3.59914875e-01  6.56557697e-01 -7.41011125e-01
   8.02409105e-01  8.43279769e-02 -5.00514033e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.25713724e+00  8.93031107e-01  7.95686538e-01 -1.26279891e+00
  -1.65827960e+00 -6.88607851e-01  4.86894603e-01 -3.60424223e-01
  -5.57474100e-01]
 [-4.54512361e-01 -5.44171638e-01  5.59167508e-01  6.89073915e-01
   1.25394223e-01  2.06370476e-01 -5.41372321e-01 -3.60424223e-01
  -5.57474100e-01]
 [-3.42164704e-01 -1.52687437e+00  4.06125783e-01 -5.28430917e-01
   1.20601413e+00  1.52129365e-01 -5.10728605e-02 -3.60424223e-01
   2.14202217e+00]
 [-1.33991103e-01 -5.44171638e-01  7.88730096e-01 -6.83034705e-01
   5.81077316e-01  7.07676992e-02 -4.05178026e-01 -3.60424223e-01
   7.92274036e-01]
 [ 1.20426776e+00  9.17598676e-01  7.74817212e-01 -1.01156775e+00
  -1.64526008e+00 -3.76721464e-01  1.12360293e-01 -3.60424223e-01
   3.60424932e+00]
 [-3.09121275e-01 -1.07237436e+00  5.59167508e-01 -1.03270499e-01
   9.97701859e-01  1.25008810e-01 -2.89412876e-01 -3.60424223e-01
   1.17399968e-01]
 [-5.04077504e-01 -7.16144616e-01  6.35688371e-01 -2.38548814e-01
  -1.78204638e-02  1.38569088e-01 -1.25979722e-01 -3.60424223e-01
  -5.57474100e-01]
 [-1.83391029e-02 -6.30158127e-01  7.46991444e-01 -6.25058284e-01
  -4.47464524e-01  1.79249921e-01 -1.02145721e-02 -3.60424223e-01
   1.91706415e+00]
 [-8.08077048e-01  1.72832843e+00 -1.85471789e+00  1.82927685e+00
   8.54487173e-01 -6.88607851e-01 -1.46408867e-01  9.69094524e-01
   4.54837002e-01]
 [ 4.22443714e+00 -3.33259064e+00 -1.85471789e+00  1.28816359e+00
  -3.66328521e+00  9.78882545e-02  2.94520162e+00  6.18330086e+00
   2.59193822e+00]
 [-1.80929294e+00  1.17555814e+00 -6.44296968e-01  2.05937077e-01
   2.50796583e+00 -6.88607851e-01 -9.43145490e-01 -3.60424223e-01
  -5.57474100e-01]
 [-5.70164362e-01 -7.03860832e-01  6.21775487e-01  3.99191812e-01
   6.72213935e-01  1.92810198e-01 -6.70756901e-01 -3.60424223e-01
  -5.57474100e-01]
 [-2.06686646e-01 -9.37252730e-01  6.98296349e-01 -5.28430917e-01
   6.33155384e-01  1.38569088e-01 -1.87267155e-01 -3.60424223e-01
  -5.57474100e-01]
 [-1.90164932e-01 -3.10779739e-01  8.58294516e-01 -2.57874287e-01
  -3.82366939e-01  5.72074215e-02 -3.64319738e-01 -3.60424223e-01
   2.59193822e+00]
 [-5.27207904e-01 -2.61644602e-01  6.07862602e-01  8.99842361e-02
   2.81628426e-01  7.07676992e-02 -5.95850039e-01 -3.60424223e-01
  -5.57474100e-01]
 [-3.65295104e-01 -8.14414889e-01  6.63514139e-01 -2.77199761e-01
   2.16530841e-01  1.11448532e-01 -1.87267155e-01 -3.60424223e-01
  -5.57474100e-01]
 [-8.41120477e-01 -7.16144616e-01  5.93949718e-01  1.32681454e+00
   4.72771210e-02  2.47051309e-01 -6.84376330e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.76617126e-01  5.77337855e-02  5.66123950e-01 -1.61246920e-01
  -8.77108583e-01  5.72074215e-02  1.70242868e-02 -3.60424223e-01
  -5.57474100e-01]
 [-6.65990305e-01 -3.68513524e-03  6.56557697e-01  2.05937077e-01
  -3.04249837e-01  2.06370476e-01 -6.43518042e-01 -3.60424223e-01
  -5.57474100e-01]
 [-3.45469047e-01 -2.12509466e-01  6.63514139e-01 -3.73827128e-01
   5.94096833e-01  5.72074215e-02 -6.16279183e-01 -3.60424223e-01
  -5.57474100e-01]
 [ 1.24061553e+00  1.21240950e+00 -1.85471789e+00 -8.37638493e-01
   6.02966379e-02 -5.53005074e-01  1.73307240e+00 -3.60424223e-01
   3.42357991e-01]
 [-9.60076820e-01  5.24517583e-01 -1.85471789e+00  2.13848443e+00
   7.89389588e-01 -4.98763964e-01  2.96222591e-01  1.32224794e+00
  -4.44995089e-01]
 [-2.00077961e-01 -8.75833810e-01  5.31341740e-01 -4.70454496e-01
   4.24843113e-01  1.52129365e-01 -1.46408867e-01 -3.60424223e-01
   2.81689624e+00]]

The data is now ready for various algorithms to be applied on it and predict the results. The classification models are available in sklearn library.

# K-Nearest Neighbors (K-NN)

## Training the K-NN model on the Training set

In [86]:
from sklearn.neighbors import KNeighborsClassifier
classifier1 = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier1.fit(X_train, y_train)

KNeighborsClassifier()

## Predicting the Test set results

In [87]:
y_pred1 = classifier1.predict(X_test)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

[[7 7]
 [1 1]
 [2 2]
 [6 6]
 [2 5]
 [2 2]
 [1 2]
 [2 2]
 [2 1]
 [1 2]
 [2 1]
 [1 2]
 [2 3]
 [2 2]
 [2 2]
 [7 7]
 [1 2]
 [2 1]
 [1 3]
 [2 3]
 [5 5]
 [1 2]
 [7 7]
 [7 7]
 [1 2]
 [1 1]
 [7 7]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 2]
 [1 3]
 [1 1]
 [1 3]
 [1 2]
 [7 7]
 [2 2]
 [2 6]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 1]
 [2 2]
 [1 1]
 [5 2]
 [7 7]
 [2 1]]

## Making the Confusion Matrix

In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
accuracy_score(y_test, y_pred1)

[[ 9  5  0  0  0  0]
 [ 8 15  0  1  0  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]

0.6111111111111112

In [89]:
from sklearn.metrics import r2_score
r1 = r2_score(y_test,y_pred1)

In [90]:
r1

0.7154457498272287

K-NN model predicts the data with an r2 score of **71.54%**

# Kernel SVM

## Training the Kernel SVM model on the Training set

In [108]:
from sklearn.svm import SVC
classifier2 = SVC(kernel = 'rbf', random_state = 0)
classifier2.fit(X_train, y_train)

SVC(random_state=0)

## Predicting the Test set results

In [109]:
y_pred2 = classifier2.predict(X_test)
print(np.concatenate((y_pred2.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

[[7 7]
 [1 1]
 [2 2]
 [6 6]
 [5 5]
 [2 2]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [2 2]
 [2 3]
 [2 2]
 [2 2]
 [7 7]
 [1 2]
 [2 1]
 [1 3]
 [2 3]
 [5 5]
 [1 2]
 [7 7]
 [7 7]
 [2 2]
 [1 1]
 [7 7]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 2]
 [2 3]
 [1 1]
 [1 3]
 [1 2]
 [7 7]
 [2 2]
 [2 6]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [7 7]
 [2 1]]

## Making the Confusion Matrix

In [110]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
accuracy_score(y_test, y_pred2)

[[10  4  0  0  0  0]
 [ 6 18  0  0  0  0]
 [ 2  3  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]

0.7037037037037037

In [111]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred2)
print(r2)

0.8274015203870076

Kernel SVM model predicts the data with an r2 score of **82.74%**

Same as the last...

# Naive Bayes

## Training the Naive Bayes model on the Training set

In [112]:
from sklearn.naive_bayes import GaussianNB
classifier3 = GaussianNB()
classifier3.fit(X_train, y_train)

GaussianNB()

## Predicting the Test set results

In [113]:
y_pred3 = classifier3.predict(X_test)
print(np.concatenate((y_pred4.reshape(len(y_pred3),1), y_test.reshape(len(y_test),1)),1))

[[7 7]
 [1 1]
 [2 2]
 [6 6]
 [2 5]
 [1 2]
 [1 2]
 [1 2]
 [2 1]
 [1 2]
 [2 1]
 [1 2]
 [1 3]
 [2 2]
 [1 2]
 [7 7]
 [1 2]
 [2 1]
 [1 3]
 [3 3]
 [2 5]
 [1 2]
 [7 7]
 [7 7]
 [1 2]
 [3 1]
 [7 7]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [6 1]
 [3 2]
 [2 2]
 [1 2]
 [2 3]
 [1 1]
 [3 3]
 [1 2]
 [7 7]
 [5 2]
 [6 6]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [2 2]
 [7 7]
 [1 1]]

## Making the Confusion Matrix

In [114]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred3)
print(cm)
accuracy_score(y_test, y_pred3)

[[ 9  3  1  0  1  0]
 [17  5  1  1  0  0]
 [ 2  1  2  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  7]]

0.46296296296296297

In [115]:
from sklearn.metrics import r2_score
r3 = r2_score(y_test,y_pred4)
print(r3)

0.5988251554941257

Naive Bayes model predicts the data with an r2 score of **59.88%**

The predictions of the models till now were ok-great... Let's have a look at Logistic Regression!

# Logistic Regression

*What is Logic Regression?*

Logistic Regression is a type of classification method. It is used to model and predict the probability of a class or an event.

![Screenshot 2021-10-04 112640.jpg]()

Basically, the probabilty of accurance of an event is plotted. The values of probability above the threshold, (eg:0.8) form a part of the event 1 and the values below the threshold form a part of event or class 0

## Training the Logistic Regression model on the Training set

In [116]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(X_train,y_train)

LogisticRegression(random_state=0)

The class LogisticRegression() from the sklearn library is applied for training the model

## Predicting the Test set results

In [117]:
y_pred4 = classifier4.predict(X_test)
print(np.concatenate((y_pred4.reshape(len(y_pred4),1), y_test.reshape(len(y_test),1)),1))

[[7 7]
 [1 1]
 [2 2]
 [2 6]
 [2 5]
 [2 2]
 [1 2]
 [2 2]
 [2 1]
 [2 2]
 [2 1]
 [1 2]
 [2 3]
 [2 2]
 [2 2]
 [7 7]
 [1 2]
 [1 1]
 [1 3]
 [2 3]
 [5 5]
 [1 2]
 [7 7]
 [7 7]
 [1 2]
 [1 1]
 [7 7]
 [1 1]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [1 2]
 [1 2]
 [1 3]
 [1 1]
 [1 3]
 [1 2]
 [7 7]
 [5 2]
 [6 6]
 [2 2]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [2 2]
 [2 1]
 [2 2]
 [1 1]
 [6 2]
 [7 7]
 [1 1]]

## Making the Confusion Matrix

In [118]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred4)
print(cm)
accuracy_score(y_test,y_pred4)

[[11  3  0  0  0  0]
 [10 12  0  1  1  0]
 [ 3  2  0  0  0  0]
 [ 0  1  0  1  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]

0.5925925925925926

In [119]:
from sklearn.metrics import r2_score
r4 = r2_score(y_test,y_pred5)
print(r4)

0.6408085694540429

The Logistic Regression model predicts the data with an r2 score of **64.08%**

# Deterining the final model

In [120]:
r = np.array([r1,r2,r3,r4])
val = np.array(["K-Nearest Neighbors","Kernel SVM","Naive Bayes","Logistic Regression"])
np.concatenate((val.reshape(len(val),1),r.reshape(len(r),1)),1)

array([['K-Nearest Neighbors', '0.7154457498272287'],
       ['Kernel SVM', '0.8274015203870076'],
       ['Naive Bayes', '0.5988251554941257'],
       ['Logistic Regression', '0.6408085694540429']], dtype='<U32')

As we can see above, **Kernel SVM** has the highest r2 score: **0.827** therefore its predictions will be used as final predictions.

# Computing the accuracy with k-fold cross validation

In [121]:
# 10 parts, mean
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier2, X=X_train,y=y_train,cv=10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 70.00 %
Standard Deviation: 11.11 %

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  UserWarning,

In [122]:
accuracies

array([0.8125, 0.6875, 0.75  , 0.5   , 0.875 , 0.625 , 0.5625, 0.6875,
       0.6875, 0.8125])

# Final predictions

In [123]:
Predictions = pd.DataFrame({"Actual values" : y_test, "Predicted values" : y_pred2})

In [124]:
Predictions

    Actual values  Predicted values
0               7                 7
1               1                 1
2               2                 2
3               6                 6
4               5                 5
5               2                 2
6               2                 1
7               2                 2
8               1                 2
9               2                 2
10              1                 2
11              2                 2
12              3                 2
13              2                 2
14              2                 2
15              7                 7
16              2                 1
17              1                 2
18              3                 1
19              3                 2
20              5                 5
21              2                 1
22              7                 7
23              7                 7
24              2                 2
25              1                 1
26              7                 7
27              1                 1
28              2                 2
29              2                 2
30              1                 1
31              1                 1
32              2                 2
33              2                 1
34              2                 1
35              3                 2
36              1                 1
37              3                 1
38              2                 1
39              7                 7
40              2                 2
41              6                 2
42              2                 2
43              1                 1
44              2                 2
45              2                 2
46              1                 1
47              2                 2
48              1                 1
49              2                 2
50              1                 1
51              2                 2
52              7                 7
53              1                 2

The confusion matrix...

In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)

[[10  4  0  0  0  0]
 [ 6 18  0  0  0  0]
 [ 2  3  0  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  1  0  0  1  0]
 [ 0  0  0  0  0  7]]

In [126]:
accuracy_score(y_test, y_pred1)

0.6111111111111112

* The results predicted by the Logistic Regression model have been the most accurate with an r2 score: **0.827**

* Thd accuracy score is quite great: 61.11%


Thus the best model that could be used to predict the type of glass on the features similar to the given features, is the **Kernel SVM**